CREATE SEQUENCE IF NOT EXISTS AUTOINC START WITH 1 INCREMENT BY 1 CACHE 1;
CREATE TABLE STUDENTS (
  ID         INT NOT NULL DEFAULT AUTOINC.NEXTVAL PRIMARY KEY,
  FNAME      VARCHAR,
  SNAME      VARCHAR,
  UNIVERSITY VARCHAR
);
