INSERT INTO STUDENTS (FNAME, SNAME, UNIVERSITY)
VALUES ('VASJA', 'PUPKIN', 'LU');
INSERT INTO STUDENTS (FNAME, SNAME, UNIVERSITY)
VALUES ('JANIS', 'PASKALISTS', 'RTU');
INSERT INTO STUDENTS (FNAME, SNAME, UNIVERSITY)
VALUES ('PETJA', 'IVANOV', 'TSI');
INSERT INTO STUDENTS (FNAME, SNAME, UNIVERSITY)
VALUES ('IVAN', 'PETROV', 'LU');
INSERT INTO STUDENTS (FNAME, SNAME, UNIVERSITY)
VALUES ('FEDJA', 'SIDOROV', 'RTU');
INSERT INTO STUDENTS (FNAME, SNAME, UNIVERSITY)
VALUES ('JANIS', 'BERZINS', 'TSI');
INSERT INTO STUDENTS (FNAME, SNAME, UNIVERSITY)
VALUES ('JURIS', 'PASKALISTS', 'RTU');